### ISSUE TITLE
Error occurs, crashes HomeAssistant

### ISSUE THREAD

**Issue by poiromaniax** [kongo09/hass-onkyo-ng#2]
Hi,

I have the same "Unknown error occured" as here:
https://github.com/kongo09/hass-onkyo-ng/issues/1

But after closing the setup window, this crashes my HomeAssistant and it stops responding for 5minutes. When it responds again, it appears as though some of the HA internal networking has died and requires a restart to resolve

Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

**Comment by kongo09** [comment]
Apologies, I never finished the integration, so no surprise that it doesn't work.

**Comment by poiromaniax** [comment]
Ah ok.

Pity, because it had such promise!

**Comment by brianharwell** [comment]
Please set this repo to private

**Comment by Nailik** [comment]
jeah i mean "it's full of bugs" - still didn't expect it would crash my HomeAssistant :D

**Comment by dannytrigo** [comment]
I have got it to a working state and supporting multiple zones. I'm happy to take over a working fork if @kongo09 is ok with that (with credit given of course)

**Comment by kongo09** [comment]
I'm totally fine if someone takes over - I just don't find the time.

My main motivations were
- support config flow instead of yaml
- support the extra capabilities a media_player entity can bring for more control
- add the further control capabilities Onkyo offers as further entities to the device
- help the integration to auto discover the capabilities so that a range of devices are supported. Alternatively, the are these Excel files of the codes so this could all be stored in data structures of the integration and maybe that is even the more efficient way than cycling through the options to identify what the device can do

**Comment by poiromaniax** [comment]
@dannytrigo thanks for taking it up! Patiently waiting for yours to be "GA" 😛
